### ISSUE TITLE
response (IncomingMessaging) has been read by interceptor and make downstream library unreadable

### ISSUE THREAD

**Issue by chaoyangnz** [mswjs/interceptors#113]
I am using Axios to get the raw stream, but Interceptors read the stream in `utils/getIncomingMessageBody`, so that the downstream http client cannot read the stream anymore. This can be a side effect and ideally that stream should be piped and not touch the original stream.

**Comment by kettanaito** [comment]
Hey, @chaoyangnz. Thanks for reporting this. I can confirm that the raw stream is no longer readable once `getIncomingMessageBody` is executed. 

Please, do you have a suggestion on how to clone the original `IncomingMessage` stream to extract its data without locking it for further reads? I've been researching this topic for some time without use.

**Comment by chaoyangnz** [comment]
@kettanaito no idea how to clone a Readable. But I suppose you need to override `IncomingMessage.on()` method, then wrap the downstream caller's callback, rather than this intercepter listen. along this approach, once the downstream callers consume the response stream, then trigger your logic of populating response body by the way.
Haven't looked into this code base, I guess interceptor's `response` event should be happening after downstream callers' response handling. that means it should happen the last.

**Comment by noahlaux** [comment]
isn't this issue happening because the response has to be cloned like here https://stackoverflow.com/q/45618984

**Comment by thomas-p-wilson** [comment]
@kettanaito I'm happy to take this on. Will advise on progress.

**Comment by kettanaito** [comment]
@noahlaux, not sure that thread is relevant, as we are not in the browser context (no service workers in place). The root cause may still be that the interceptors library may need to clone the original response, once I have a clear understanding of how to do that. 

@thomas-p-wilson, that would be superb, let me know if you need any help with this.

**Comment by noahlaux** [comment]
@kettanaito For me it was relevant, I am using the interceptors in a browser context (namely `XMLHttpRequest` & `fetch`) and `fetch` is pretty much useless because of this issue which is why I linked to a possible solution because the issue is the same in the serviceworker context: they HAVE to read the response, yet still pipe it further down to the client.
