### ISSUE TITLE
xhr.upload is null

### ISSUE THREAD

**Issue by jameskerr** [mswjs/interceptors#121]
I've got code that looks like this:

```js
const xhr = new XMLHttpRequest()
xhr.upload.addEventListener("progress", (e) => {
  // ...
})
```
When I run my test I get this error:
```
    TypeError: Cannot read property 'addEventListener' of null

      40 |         const xhr = new XMLHttpRequest()
      41 |         console.log(xhr)
    > 42 |         xhr.upload.addEventListener("progress", (e) => {
```

That console.log reveals that the upload property of the class is set to null.

```
   XMLHttpRequestOverride {
      upload: null
    }
```

If someone points me in the right direction, I'd be open to filling in this gap.

**Comment by kettanaito** [comment]
Hey, @jameskerr. Thank you for raising this up.

The `upload` property of the XMLHttpRequest override class is currently set to `null` in the constructor and isn't modifier since then:

https://github.com/mswjs/interceptors/blob/d693b1ee90479f7e6bd48b5d9a08b33b663d2139/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L134

According to the documentation, `XMLHttpRequest.upload` is an `XMLHttpRequestEventTarget` with the support for certain progress events. My initial thought is to introduce a custom event handling for the `upload` property, similar to how the regular `xhr.addEventListner()` events are collected and executed at the right stage of the request:

https://github.com/mswjs/interceptors/blob/d693b1ee90479f7e6bd48b5d9a08b33b663d2139/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L463-L481

https://github.com/mswjs/interceptors/blob/d693b1ee90479f7e6bd48b5d9a08b33b663d2139/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L277

https://github.com/mswjs/interceptors/blob/d693b1ee90479f7e6bd48b5d9a08b33b663d2139/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L159-L183

What do you think about this approach?

**Comment by kettanaito** [comment]
We may want to put this issue on hold. It's possible we'll rewrite the XHR interception from the ground-up to extend the native XMLHttpRequest class instead of patching it (similar to what we did with `ClientRequest` in #164).

**Comment by kettanaito** [comment]
@johnsonlin has kindly provided us with a temporary fix where `this.upload` is set to an empty object until we decide to implement a proper polyfill for it (see #187). I'm closing this issue in favor of the said polyfill proposal.
