### ISSUE TITLE
Modify requests

### ISSUE THREAD

**Issue by PaperStrike** [mswjs/interceptors#185]
Hello!

I would like to propose a feature that will allow us to modify the sent requests. That is, apart from returning responses from the `resolver`, we should be able to return requests as well. In that case, the returned request should be treat as the real request to send. This allows us to intercept the network in all aspects.

My initial motivation is to bypass specific requests without exposing specific headers. I know there is a relevant #34, which suggests this is what should be done in downstream packages, but it seems this upstream interceptor don't have the ability to allow so. Take the `x-msw-pass` as an example, if we simply return a falsy value on this header's existence, the request will pass through, but be sent with this header. Allowing modifying headers would be a solution, but why not being able to modify the whole request?

Thanks!

**Comment by kettanaito** [comment]
Hey, @PaperStrike. Thanks for suggesting this.

You can modify outgoing requests at the moment by accessing the second argument of the `resolver` function:

```js
createInterceptor({
  modules: [...],
  resolver(req, ref) {
    // use "ref" to operate on the raw request instance
  }
})
```

While `req` is an isomorphic request representation, the `ref` is a reference to the actual request instance. That instance is different depending on what made the request:

- `ClientRequest` if the request was issued by `http`/`https`;
- `XMLHttpRequest` if the request was issued by the respective class;
- `Request` if the request was issued by `fetch` (applicable only when used in a browser). 

Access that ref, and call the respective methods you wish to modify the request. 

It's worth mentioning that you should be careful modifying things that weren't set by you (like the `x-msw-bypass` header). This may break the functionality that depends on those things (such as life-cycle events if you remove the said header).

**Comment by PaperStrike** [comment]
This isn't true at least for `fetch`. You can see the `pureFetch` isn't using the `ref`. So this is a bug?

https://github.com/mswjs/interceptors/blob/1d35db531d14a7f95126a382b005451af927924c/src/interceptors/fetch/index.ts#L61

**Comment by PaperStrike** [comment]
@kettanaito Also the changes we can made in `ref` are _very_ limited. For [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request), most properties of it are `readonly`. Actually we can only change the `headers`.

And this seems not to be a "bug" that we can't change the request via `ref`, since it will be an breaking change if we start to support it - users may have already been using `ref`'s [body functions](https://developer.mozilla.org/en-US/docs/Web/API/Request#methods), which can only run once.

**Comment by kettanaito** [comment]
Fetch interceptor provides the `ref` when calling the `resolver` function right here:

https://github.com/mswjs/interceptors/blob/1d35db531d14a7f95126a382b005451af927924c/src/interceptors/fetch/index.ts#L41

Interceptors do not use the `ref` internally, it's only for the public API.

**Comment by kettanaito** [comment]
> Also the changes we can made in ref are very limited. For Request, most properties of it are readonly. Actually we can only change the headers.

I believe there's a good reason for that. Certain request instances treat properties of already instantiated request as readonly. I'd respect those limitations to guarantee resilient request execution. 

Re-constructing the request based on its representation on our side would be unreliable and go against what this library is designed to do. This would be a very confusing flow:

```
request -> interceptor -> resolver -> request* -> mock/bypass
```

Mutating (I treat reconstruction of the request as the original request's mutation as we're still in its context) mustn't happen as it will bring more harm than use. In certain cases, that'd mean reconstruction of the entire request module, since request instances like `ClientRequest` represent the entire request on their own. 

I think if you're looking for request modification to strip some sensitive or undesirable data from requests this isn't the right tool to achieve that. 

> And this seems not to be a "bug" that we ain't using ref in the bypassed 

Ref is passed _before_ any mocked/bypass resolution. We always execute the resolver first, then depending on whether it's returned a mocked response either mock the response or call the request module as-is. You always get the `ref` no matter what kind of request will happen at the end (mocked/bypassed).

**Comment by PaperStrike** [comment]
> Interceptors do not use the `ref` internally, it's only for the public API.

@kettanaito So we can't use it to alter the request, unlike what you said:

> You can modify outgoing requests at the moment by accessing the second argument of the `resolver` function:

**Comment by kettanaito** [comment]
Yes, you are right in pointing out that `pureFetch` doesn't use the constructed `ref` request 👍 I see what you mean now.

https://github.com/mswjs/interceptors/blob/1d35db531d14a7f95126a382b005451af927924c/src/interceptors/fetch/index.ts#L61

We should have `pureFetch(ref)` instead here. Thanks for reporting this. Would you be interested in opening a pull request with the fix?

That being said, unlike `fetch`, other request modules (http/XHR) utilize request instances that can be mutated before the request is made.

**Comment by PaperStrike** [comment]
@kettanaito 

> That's why we've raised mswjs/msw#713 to discuss an alternative implementation. I'd love for you to join the discussion and share your ideas there. Thanks!

I'm looking into that, trying my best.

> I think if you're looking for request modification to strip some sensitive or undesirable data from requests this isn't the right tool to achieve that.

FWIW, this tool can achieve that, at the moment. Right now to modify the requests I am using something like

```js
let bypassNext = false;

// the goal is to bypass all requests from this function.
const bypassFetch = (...args) => {
  bypassNext = true;
  return fetch(...args);
};

createInterceptor({
  modules: [interceptFetch],
  async resolver(request) {
    if (bypassNext) {
      bypassNext = false;
      return;
    }
    const modifiedRequest = getModifiedExample(request);
    return bypassFetch(modifiedRequest);
  },
});
```

The same applies to other interceptor modules.
But I'm unsure if it's reliable in high concurrency cases, which is why I filed this issue proposing native supports.

**Comment by PaperStrike** [comment]
Following

> But I'm unsure if it's reliable in high concurrency cases, which is why I filed this issue proposing native supports.

As you told me it's expected that the headers should be modifiable via the second argument, this should be reliable:

```js
const bypassHeaderName = 'x-msw-bypass';

// the goal is to bypass all requests from this function.
const bypassFetch = (...args) => {
  const request = new Request(...args);
  request.headers.set(bypassHeaderName, '');
  return fetch(request);
};

createInterceptor({
  modules: [interceptFetch],
  async resolver(request, ref) {
    if (ref.headers.has(bypassHeaderName)) {
      ref.headers.delete(bypassHeaderName);
      return;
    }
    const modifiedRequest = getModifiedExample(request);
    return bypassFetch(modifiedRequest);
  },
});
```

**Comment by kettanaito** [comment]
I wouldn't limit you in any sort of request modification, as long as our API gives you the means to do that. I was simply explaining that this particular library won't be tailored to support request modifications as the primary feature (the request reference is primarily exposed for introspection/response logic purposes).

**Comment by RomanDavlyatshin** [comment]
@kettanaito greetings 😃! Is there a way to modify headers after `createInterceptor` function was deprecated in #235 ?
I've poked around in sources a bit and haven't figured it out, so the example would really help 👍 🙏

**Comment by kettanaito** [comment]
Hey, @RomanDavlyatshin. Give the "request" event a try. I'd expect the request reference to be modifiable at the time being. 

This is a good thing to keep in mind while I'm working on #292: should the intercepted requests be modifiable? 🤔

**Comment by RomanDavlyatshin** [comment]
> Hey, @RomanDavlyatshin. Give the "request" event a try. I'd expect the request reference to be modifiable at the time being.

@kettanaito hey )
I've actually tried the `request` reference right away, but it does not seem to work. To be exact - the header _is_ set, but when the actual request is received on target webserver, there is no injected header present.

1. The code
```javascript
const Interception = require('@mswjs/interceptors')
const {FetchInterceptor} = require('@mswjs/interceptors/lib/interceptors/fetch')
const {ClientRequestInterceptor} = require('@mswjs/interceptors/lib/interceptors/ClientRequest')
const {XMLHttpRequestInterceptor} = require('@mswjs/interceptors/lib/interceptors/XMLHttpRequest')

const interceptor = new Interception.BatchInterceptor({
  name: 'my-interceptor',
  // I really wanted to make sure to intercept any request regardless of the platform
  // though I might try to define platform first and only employ appropriate interceptors
  interceptors: [
    new FetchInterceptor(),
    new ClientRequestInterceptor(),
    new XMLHttpRequestInterceptor(),
  ]
})

interceptor.apply()

interceptor.on('request', (request) => {
  console.log(request.headers)
  request.headers.set('x-my-custom-header', 'fizbuz')
  console.log(request.headers) // 'x-my-custom-header' is present'
})
```
2. Header is present in `request.headers` map
![image](https://user-images.githubusercontent.com/34244611/196497540-caa2e588-014a-4000-854d-cebd7966b5ef.png)

3. But is absent when the request is accepted on the server (a simple Koa app which logs headers for whatever request is received)
![image](https://user-images.githubusercontent.com/34244611/196497658-e8be9500-af9e-4c74-8245-639827986eee.png)

@kettanaito do you have idea why that might happen?

I have a few far-fetched guesses 😄:
1. The request headers are serialized before the interceptor is called, and thus the modified `request.headers` Map is not used at all;
2. The request object passed to the interceptor is some sort of deep copy (even weirder) not used in producing the actual request;

> This is a good thing to keep in mind while I'm working on #292: should the intercepted requests be modifiable? 🤔
It really depends on a task at hand, but I would like your tool to provide that, since my case requires it. (I'm developing a tool which injects additional data to requests made from API tests to improve traceability)

If you are concerned about users modifying requests by accident, I would suggest to make it obvious with 
- either parameter for interceptor's constructor ( e.g. `new FetchInterceptor({ modifiable: true})`) 
- or even separate interceptor type ( `import ModifiableFetchInterceptor from ...`)
That way no one could miss it

**Comment by kettanaito** [comment]
Thanks for the feedback, @RomanDavlyatshin. 

I've added the support to modify outgoing request headers in #292. But there still won't be any support for modifying any other request info like url, method, or body. This library is not a full-scale proxy at this point, and unless there's a really good reason, it won't be.
