### ISSUE TITLE
POST requests with body from Axios are not intercepted

### ISSUE THREAD

**Issue by massimopalmieri** [mswjs/interceptors#238]
Hi all,

when making a POST request with a body through axios, the request hangs. 

small reproduction:

```js
  // doesn't work
  axios.post('http://localhost:5001/one', {name: 'hello'})
  
  // works
  axios.post('http://localhost:5001/two')

  // works
  fetch('http://localhost:5001/three', {
    method: 'POST',
    body: JSON.stringify({name: 'hello'})
  })
```

node version: 16.13.1
msw version: 0.39.2

**Comment by kettanaito** [comment]
Hey, @massimopalmieri. Thanks for reporting this!

It's a known issue and we're tracking it in https://github.com/mswjs/msw/issues/1125.

**Comment by massimopalmieri** [comment]
thanks @kettanaito

**Comment by karthikkpati** [comment]
@kettanaito Is there a workaround if we are just using `@mswjs/interceptors` library?

**Comment by kettanaito** [comment]
Hey, @karthikkpati. No, as the issue is in the interceptors library. I've opened a pull request with the solution to `follow-redirect` repo, they seem to be okay with the fix. At the same time, one of their maintainers has highlighted that we may be doing write callbacks wrong as a part of the interceptor (although this was a conscious decision to preserve the semantics of callbacks), so we may introduce a change on the interceptors side to change how we call write callbacks. I haven't decided on that yet.

**Comment by Jaanilj** [comment]
Noticed this today as well and thought I was going crazy. Nice to see so fast response to this issue as I'm eager to migrate away from `nock` 👍

**Comment by kettanaito** [comment]
I believe we are at the final stage of code review regarding the change to `follow-redirects`. It'd then have to be updated in `axios`, which I'm planning on doing.
