### ISSUE TITLE
The `EventEmitter` property is not defined on the browser side

### ISSUE THREAD

**Issue by lenqwang** [mswjs/interceptors#276]
![image](https://user-images.githubusercontent.com/5085523/180970027-7a87f8aa-cc65-4ab2-93fb-afa164874958.png)
![image](https://user-images.githubusercontent.com/5085523/180970182-76d20c46-a136-4351-a5b7-0680c25c153f.png)

When I using this module in the browser, I can't find the 'EventEmitter' property in the console output. I guess this is because the 'strict-event-emitter' module relies on the native 'events' module of Node.js. Is there any way to solve this problem?

**Comment by hiteshkalwani** [comment]
Hi @lenqwang ,

you should use `evenemitter3` which is browser compatible. you can take the reference from it's github repo https://github.com/primus/eventemitter3. We were also getting the same error with `events`, which is not compatible with Browser i guess so.

**Comment by kettanaito** [comment]
I think `StrictEventEmitter` cannot run in the browser because it extends `EventEmitter`, which is not a thing in the browser. 

We should write a different module for it that'd be imported in the browser, and use `EventTarget` as the base class instead. The issue here is that `EventTarget` and `EventEmitter` are not compatible, as emitter has more properties and is, generally, a totally different thing. 

Strange that I've never encountered this while working with Interceptors + MSW in the browser. How are you getting this error?

**Comment by kettanaito** [comment]
I'm moving forward with this by ditching `EventEmitter` and utilizing `EventTarget` + type-safety in https://github.com/open-draft/strict-event-emitter/pull/8. Afaik, we should be fine with the interface EventTarget provides. Will see.

**Comment by lenqwang** [comment]
> I'm moving forward with this by ditching `EventEmitter` and utilizing `EventTarget` + type-safety in https://github.com/open-draft/strict-event-emitter/pull/8. Afaik, we should be fine with the interface EventTarget provides. Will see. 

Thanks @kettanaito

**Comment by kettanaito** [comment]
## Released: v0.19.5 🎉

This has been released in v0.19.5!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.19.5)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.19.5)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
