### ISSUE TITLE
XMLHttpRequestOverride: remove `getResponseXML` and `responseXML`, drop xmldom

### ISSUE THREAD

**Issue by LoneRifle** [mswjs/interceptors#297]
XMLHttpRequestOverride contains a property `responseXML`, which appears to have a meaningful value given only the appropriate response content type (`application/xml` or `text/xml`). This suggests that the property is only useful when dealing with XML responses, which would form a smaller proportion to JSON or HTML responses, amongst others.

To support this property however, XMLHttpRequestOverride implements `getResponseXML()`, a thin wrapper around xmldom. This package has a significant size (134kB for 0.8.5) relative to what it is being used for, obliges a dependent to maintain it even if it does not process XML, and is currently maintained only by [one active author](https://github.com/xmldom/xmldom/graphs/contributors).

Given that the few applications who actually depend on this property would in all likelihood explicitly bring in a package to parse and manipulate the response, I would consider it reasonable to propose the removal of `XMLHttpRequestOverride.responseXML` and its supporting cast. Dependents on this property will not be too inconvenienced, as they can trivially build an XML document from `responseText`, even reproducing `getResponseXML()` to do so. 

Most other users of this package would stand to benefit by no longer depending on - and having to maintain - a package of little relevance to them.

**Comment by kettanaito** [comment]
Hey, @LoneRifle. Thanks for the proposal.

I think that us depending on `xmldom` was incorrect, to begin with. This library is not a polyfill but it acts like one by taking the responsibility of parsing XML response bodies. 

What we should do is rely on whichever `XMLHttpRequest` implementation is present in the environment. It's a shame we cannot do `Override extends XMLHttpRequest` because this syntax will get transpiled by TypeScript into code that won't run in the browser (works fine in Node.js). It'd be much better to have a class extension instead of a stub, similar to what we do with `NodeClientRequest` extending `http.ClientRequest`. 

Overall, I agree with this direction. 

1. Drop `xmldom`.
2. Rely on `XMLHttpRequest.prototype.responseXML` directly, if it's possible. I'd expect `responseXML` to be a getter, so setting `response` or `responseText` should suffice on our side. 

As a side note, I'm introducing quite a number of breaking changes in #292, so I'd address this proposal after that.

**Comment by kettanaito** [comment]
## Released: v0.18.3 🎉

This has been released in v0.18.3!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.18.3)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.18.3)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
