### ISSUE TITLE
How to use with conjunction with MSW setupServer?

### ISSUE THREAD

**Issue by WesleyYue** [mswjs/interceptors#306]
Apologies if this is an obvious question. I'm trying to use msw interceptors to instrument and trace all of the HTTP requests for a node application. I am able to set up, individually:
1. A MSW setupServer + Jest configuration where I call server.listen() before each test. This allows me to mock server responses during tests.
2. Interceptors that log outgoing HTTP requests and responses using this mswjs/interceptors. This allows me to trace and instrument code during production.

When I combine the two, the Interceptor will take precedence, execute the listener I put on the interceptor, and try to call the actual endpoint, rather than going through my mock server. Is there a way to combine the two?

**Comment by kettanaito** [comment]
Hey, @WesleyYue. It's a good question.

This library is precisely what MSW uses in `setupServer`. They are not meant to be used together, so you need to pick one. I highly suggest MSW because it's higher level, giving you more flexibility and less verbosity than this library. 

You can do both mocking and request logging at the same time with MSW. One of the ways for that is having different handlers for different things.

```js
// src/mocks/handlers.js
export const handlers = [
  // Let's create a handler that catches all requests
  // and logs them somehow. Note that we don't return any mocked
  // responses here so that the captured request would passthrough,
  // arriving at any matching request handler below.
  rest.all((req, res, ctx) => {
    logRequest(req)
  })

  // Here, let's mock the response in this handler.
  rest.get('/resource', (req, res, ctx) => res(ctx.text('hello'))),
]
```

You can abstract the logging handlers and do whichever setup you feel most comfortable. Let me know if that works.

**Comment by WesleyYue** [comment]
Gotcha, thank you for the great library!
