### ISSUE TITLE
Cannot read "request.text()" in the "response" event listener

### ISSUE THREAD

**Issue by ArielGueta** [mswjs/interceptors#319]
Hi,

I'm using the response interceptor and I want to read the request body, but I'm getting a ReadableStream.

```ts
interceptor.on('response',  (res, req) => {
    req.body // null | ReadableStream
})
```

In the previous versions it was a string. How can I read it now?

Thanks.

**Comment by ArielGueta** [comment]
Even when I try to read it with clone() and text() I get an error. This is a breaking change because it also was sync value before. Can you please re-support it?

**Comment by kettanaito** [comment]
Hey, @ArielGueta. Thanks for reporting this. 

Since 0.19.0, this library handles requests/responses as defined in the Fetch API specification. That implies that `request.body` is indeed a readable stream you can read. 

If you wish to read the request's body as text, you need to clone that request and call its `.text()` method that returns a Promise:

```js
interceptor.on('response', async (response, request) => {
  const requestText = await request.clone().text()
  console.log({ requestText })
})
```

If this fails for you, please create a reproduction repository/sandbox where I can look into this. Thanks.

**Comment by ArielGueta** [comment]
Thanks
