### ISSUE TITLE
XHR: Failed to construct 'Response': the status provided (0) is outside the range [200, 599]

### ISSUE THREAD

**Issue by smo043** [mswjs/interceptors#335]
@kettanaito - We encountered the error shown below. Block the request URL in the browser network tab and call the API again to reproduce it. Any ideas on how to solve the following problem?

![image](https://user-images.githubusercontent.com/17010033/218489347-a45647c7-729b-4438-b709-5928a64974d8.png)

_Originally posted by @smo043 in https://github.com/mswjs/interceptors/issues/307#issuecomment-1428061952_

**Comment by kettanaito** [comment]
Thanks for reporting this, @smo043. The issue seems to be related to this:

https://github.com/mswjs/interceptors/blob/d73624b222fd80a291486e13eb368d440bf21816/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L454

Per the specification, XHR must retain the status code `0` until it is resolved. However, creating a Fetch API Response with a 0 status code is forbidden. This indicates two problems:

1. The "response" event is emitted _before_ the XHR instance (override) is resolved.
2. The `createResponse()` utility function mustn't accept `0` as the input status code. It must throw on that and do so earlier.

**Comment by smo043** [comment]
Thank you @kettanaito - does it requires a fix in this library or I have to adjust my interceptor logic?

**Comment by kettanaito** [comment]
@smo043, it's a but on the library's side so the fix should also be done here.

**Comment by smo043** [comment]
@kettanaito - I would be more happy to help, could you pls help me with the gist with the setup to run this package in local environment.

**Comment by smo043** [comment]
@kettanaito - here is the pull request https://github.com/mswjs/interceptors/pull/336

**Comment by kettanaito** [comment]
## Released: v0.22.10 🎉

This has been released in v0.22.10!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.22.10)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.22.10)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
