### ISSUE TITLE
error: Request is not defined (from Google Secret Manager)

### ISSUE THREAD

**Issue by shiftagain** [mswjs/interceptors#352]
I'm trying to use this library in an application that uses Google Secret Manager, and I think somehow the two conflict. For some reason, every request is failing with the error message from GSM "Failed to retrieve auth metadata with error: Request is not defined". (GSM just throws 'Request is not defined'.)

Full stack trace:
```
{
   "promise":{},
   "reason":{
      "code":16,
      "details":"Failed to retrieve auth metadata with error: Request is not defined",
      "message":"16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: Request is not defined",
      "metadata":{},
      "note":"Exception occurred in retry method that was not classified as transient",
      "stack":"Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: Request is not defined
    at Object.callErrorFromStatus ([...]/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/src/client.ts:352:36)
    at Object.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at [...]/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest ([...]/node_modules/@grpc/grpc-js/src/client.ts:324:26)
    at ServiceClientImpl.<anonymous> ([...]/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at [...]/node_modules/@google-cloud/secret-manager/src/v1/secret_manager_service_client.ts:278:25
    at[...]/node_modules/google-gax/src/normalCalls/timeout.ts:54:13
    at repeat ([...]/node_modules/google-gax/src/normalCalls/retries.ts:104:19)
    at [...]/node_modules/google-gax/src/normalCalls/retries.ts:144:7
    at OngoingCallPromise.call ([...]/node_modules/google-gax/src/call.ts:81:23)
    at NormalApiCaller.call ([...]/node_modules/google-gax/src/normalCalls/normalApiCaller.ts:43:15)
    at [...]/node_modules/google-gax/src/createApiCall.ts:116:26
    at runMicrotasks (<anonymous>)"
   }
}
```

(I've removed irrelevant bits from the above paths.)

I realize this might not necessarily be an issue with this interceptors library - any recommendations nonetheless?

**Comment by kettanaito** [comment]
Hey, @shiftagain. Thanks for reporting this. 

Since recent releases, this library uses global fetch primitives like `Request` in `Response` in Node.js. We've bumped the minimal supported version of Node.js to be `>= 18` as well so make sure you're using an appropriate version of Node.js. You can always rollback to another version of this library if you aren't. 

Another possible reason for this error is if you're running a test environment that doesn't have or strips away those Node.js globals. One example of such being Jest+JSOM that's notoriously bad at stripping away Node globals. If that's the case, follow official recommendations from your test framework to ensure that you're running a complete Node.js environment.

**Comment by shiftagain** [comment]
Ah, thanks for the response. Probably my issue was that I was using a version of node < 18. Could be worth adding something to the README that notes that explicitly.

Appreciate it! @kettanaito

**Comment by kettanaito** [comment]
@shiftagain, you should get an error when installing this package since we defined the supported range of Node in our package.json. But I suppose that's package manager-specific. 

Would you have a minute to add a nice bold sentence at the beginning of the README stating that you need to use Node 18+ with this package? That'd help me out a lot.
