### ISSUE TITLE
Support node-fetch-native

### ISSUE THREAD

**Issue by hoersamu** [mswjs/interceptors#385]
[node-fetch-native](https://github.com/unjs/node-fetch-native) is a redistribution of [node-fetch v3](https://github.com/node-fetch/node-fetch) for better backward and forward compatibility.

It is used in ofetch which in turn is used by Nuxt (VueJS SSR framework).

I couldn't manage to get @mwjs/interceptors to work with it. Any ideas?

Here is a link to a demo repo: https://github.com/hoersamu/nuxt-prometheus/tree/main
Adding a FetchInterceptor did also not work (probably because globalThis.fetch is already patched by node-fetch-native)

**Comment by kettanaito** [comment]
Hi, @hoersamu. 

Yes, I suspect using a `FetchInterceptor` won't work because `node-fetch-native` is unlikely to introduce a `fetch` global (just as `node-fetch` doesn't do that). 

You should be using the `ClientRequestInterceptor`, as this is likely what `node-fetch-native` uses under the hood (`node-fetch` does). Did you give that interceptor a try? Were there any errors? 

In general, this library has a strict policy on algorithm support. We don't ship support for individual packages but rather aim to support the low-level means of making an HTTP request in Node.js, which aren't that many. This is simply a more sensible bet since supporting those algorithms automatically enables support for any third parties that will, inevitably, be using them. 

I will close the issue for now since we won't be adding support for `node-fetch-native` specifically. Please, feel free to share your discoveries here, and if we uncover an issue with the existing interceptors, we will assess the best way to address it. Thanks.

**Comment by hoersamu** [comment]
Yeah I tried all interceptors but none seemed to work. I'll try to investigate further and post an update here.

**Comment by kettanaito** [comment]
I looked at the `node-fetch-native` package, and all it does is re-export `node-fetch`, which we do support (as well as global `fetch` in Node.js). 

Take a look at this set of tests that test `node-fetch` specifically: https://github.com/mswjs/interceptors/blob/ca47c880790cabab58e667d1a81a82d25ab31a33/test/modules/fetch/intercept/fetch.test.ts#L4
