### ISSUE TITLE
Support request interception in iframes

### ISSUE THREAD

**Issue by hpohlmeyer** [mswjs/interceptors#395]
I have a use-case where I need to intercept requests in an iframe. Currently `interceptor.apply` applies the interceptor to the request API (fetch/xml) of `globalThis`, which means we can only intercept requests in the root `window`.

I am proposing a new parameter for `interceptor.apply` which defines the scope, the interceptor should be applied to. For example the `window` of an `iframe`. The default would still be `globalThis`, which means we would not introduce a breaking change. Here is an example:

```ts
// Interceptor for root requests (current default)
const rootInterceptor = new BatchInterceptor({
  name: 'root-interceptor',
  interceptors: browserInterceptors,
})
rootInterceptor.apply() // defaults to `globalThis`
interceptor.on('request', listener)

// Parallel interceptor for iframe requests
const iframeInterceptor = new BatchInterceptor({
  name: 'iframe-interceptor',
  interceptors: browserInterceptors,
})
iframeInterceptor.apply(frames[0])
interceptor.on('request', listener)
```

I can put up a PR for this if you are interested in supporting that. Let me know what you think.

**Comment by kettanaito** [comment]
Hi, @hpohlmeyer. That's an interesting proposal. 

We support request interception in iframes as a part of MSW where in-browser interception is provisioned by a Service Worker (it intercepts outgoing requests from iframes on the page by default). 

What comes to this library, I'm not sure how far we should push a similar support. This library is mainly Node.js oriented, and the fetch support is aimed to support the global fetch in Node.js more than in the browser (although it can run in both environments by design). 

How do you see this support implemented on the interceptor's side?

**Comment by hpohlmeyer** [comment]
Hey @kettanaito, thanks for taking a look!
I see, so we would duplicate features here in a package whose main aim is to support MSW.

Since it is a pretty solid standalone request interception library, having that option would be nice to have. I might be biased though, because I am using it standalone 😅. To justify adding support, I think the implementation needs to be minimal in order to not bloat the package size and to not add a lot of maintenance overhead.

As far as the implementation goes I think there are two options:

__1. One interceptor per environment__

This is the implementation that would add the least amount of code to the package.

We could add the `environment` parameter to the `apply` method and pass it down to the `setup` methods in the fetch and xml-http-request interceptors. In `setup` we are using the specified environment instead of `globalThis`.

```diff
- protected setup() {
-   const pureFetch = globalThis.fetch
+ protected setup(environment: Pick<typeof globalThis, 'fetch'> = globalThis) {
+   const pureFetch = environment.fetch

-   globalThis.fetch = async (input, init) => {
+   environment.fetch = async (input, init) => {
```

By doing it this way, we would offload some tasks to the end-user, like looking for the iframes and making sure they can be accessed (meaning: same-site).


__2. One interceptor for all request__

This behavior is probably similar to the behavior of MSW. We would look for all same-origin iframes and apply the interceptor in every environment. The end-user does not need to do anything.

```diff
- protected setup() {
-   const pureFetch = globalThis.fetch
-
-   globalThis.fetch = async (input, init) => {
+ protected setup() {
+   const environments = findEnvironments()
+   const pureFetchers = []
+
+   for (const index = 0; index < environments.length; index++) {
+     const environment = environments[index]
+     pureFetchers[index] = environment.fetch

+     environment.fetch = async (input, init) => {
```

I have written something like `findEnvironments` before, this should be around 15 lines of code. It is not much, but this approach adds to the complexity of the code.

---

I have looked at the changes needed for the first option here: https://github.com/hpohlmeyer/interceptors/commit/64cde68136a26ac14371abe15655ea793b62438c. It is not ready for a PR, but you can see what would need to be added code-wise.

**Comment by kettanaito** [comment]
If I may, what stops you from using MSW? 

This package is primarily meant for low-level request interception, requiring you to implement routing and other quality of life features by yourself. While you can certainly do that, I'd always recommend to start from MSW, since it wraps this package in Node.js and provides a more developer-friendly interface to work with. In addition, MSW ships with the iframe support you mention, requiring no changes in order to have it. 

I'd have to reason against this proposal. Interceptors are not even meant to run in the browser as of now, so adding support for a specific browser feature is out of the package's scope. 

This is somewhat related to the WebSocket support, as we would like to support it both in browser and Node.js while its in-browser support is a bit more complicated to rely on the Service Worker alone (e.g. message parsing, different transports). I think it's a similar feature application-wise as the `fetch` support. I haven't decided on how to properly represent such multi-environment features in this package. 

---

My main concern with this particular feature is that it's browser-only. I don't think that browser-only features is ever a concern for this package. It does support `fetch` in the browser tangentially, only because both the browser and Node.js implement the same Fetch API spec. 

If I were to choose between the proposed implementation options, I'd lean toward the first one. 

I recommend using MSW for this. It won't require any change on either ends, and you will have iframe support out of the box. We have tests to confirm that as well. If you still decide to use this package for iframe request interception, then I'd suggest to implement this support on your side. You can either establish the interceptor in the iframe itself (where `globalThis` will point to the iframe window) if you own that resource, or implement it from scratch.

Note that you can create custom interceptors by extending `Interceptor`, `BatchInterceptor` or even `FetchInterceptor` classes. This would be the approach I recommend for custom implementation.

```js
class FetchEnvironmentInterceptor extends FetchInterceptor {
  constructor(environment) {
    super(...)
  }

  protected setup() {
    // Apply the fetch interceptor to the custom "environment".
  }
}
```

**Comment by hpohlmeyer** [comment]
Thank you for the detailed explanation, I totally understand the reasoning.

> If I may, what stops you from using MSW?

Sure, I am happy to give you some more context: I am using '@mswjs/interceptors' in user-facing code where it is crucial to catch all requests. I also need to know more about the request, like the callstack, that lead to the request or the API that was used to send the request. While interception via service workers would be way nicer (code and performace-wise), I don’t think I can get this information from a service worker.

In the iframe scenario, I think the blocker would be the async worker registration. Deferred mounting is using this package to defer the requests until the worker has been installed, right? In its current form this would mean I would miss iframe requests during the worker installation.

**Comment by Untel** [comment]
Hi @hpohlmeyer!  
Any clues about how you overrode the interceptor class?  

I have the same issues working with iFrames, but also with injected scripts from a browser extension, which do not share the same `globalThis`.  
In fact, I don't understand why the constructor couldn't be something like `constructor(context = globalThis)`, which would be super convenient for any environment...  

While we can't access most dependencies of the [base fetch interceptor](https://github.com/mswjs/interceptors/blob/main/src/interceptors/fetch/index.ts) setup function, did you monkey-patch the package? (I would like to avoid that.)  

I tried things like this with no success:  
```ts
import { FetchInterceptor } from "@mswjs/interceptors/fetch";

export class WFetchInterceptor extends FetchInterceptor {
  constructor() {
    globalThis.fetch = window.fetch;
    super();
  }
}
```
