### ISSUE TITLE
Question: Cannot find module error

### ISSUE THREAD

**Issue by Khang-NT** [mswjs/interceptors#396]
It may be a silly question. I want to import `@mswjs/interceptors/presets/browser` into my typescript project, which is targeted to run on the browser, but the typescript compiler only resolves the `node` source code exported in your `package.json`, then leads to this error:
```
"Cannot find module '@mswjs/interceptors/presets/browser' or its corresponding type declarations."
```
![image](https://github.com/mswjs/interceptors/assets/13332950/2b8969f3-544d-412b-910f-e7ff9eb06ed4)

So what's the correct way to install `@mswjs/interceptors` to work on browser?

**Comment by kettanaito** [comment]
Hi, @Khang-NT. 

The error you're getting is caused by the code thinking you are writing it for Node.js. This is the default behavior for TypeScript and you have to change it manually to explicitly say "hey, I want this to run in the browser so I want all imports to also be browser imports". 

We explicitly define different presets based on the environment:

https://github.com/mswjs/interceptors/blob/36400ccc47bf53b269888a7a3a5f452df592f58b/package.json#L60

Sorry, I don't remember from the top of my head how to configure that in TypeScript. I suggest researching this, there must be an answer online. Once TypeScript understands your module is meant for the browser, it will resolve the `/presets/browser` import path correctly. Note that you may also have to configure other tooling, like Jest or Vitest, to handle the module imports correctly. 

> I know it's a hassle but that's actually the right way to use ambiguous modules like Interceptors, which has both Node-only and browser-only code. I wish there were more tools like this to teach us more. I also wish tools like TypeScript taught us more about conditional exports in consumer projects. Let me know about your findings.

**Comment by Khang-NT** [comment]
Thanks for your response. I find out the typescript compiler doesn't understand the `"browser"` condition, because it's treated as a custom condition, so I have to explicitly tell the compiler to pick it in `tsconfig.json`:
```json
{
  "compilerOptions": {
    "resolvePackageJsonExports": true,
    "customConditions": ["browser"]
  }
}
```

Anyway, it will work fine without extra configuration if you use `"default"` instead of `"browser"`, as stated in this guideline:
> https://nodejs.org/api/packages.html#conditional-exports
When using environment branches, always include a "default" condition where possible. Providing a "default" condition ensures that any unknown JS environments are able to use this universal implementation, which helps avoid these JS environments from having to pretend to be existing environments in order to support packages with conditional exports. For this reason, using "node" and "default" condition branches is usually preferable to using "node" and "browser" condition branches.

**Comment by kettanaito** [comment]
@Khang-NT, that's an interesting find. The `browser` export is quite standardized between the bundlers but I suppose it's not a part of the official spec? The more I learn about export conditions the more I realize I don't know. 

> Anyway, it will work fine without extra configuration if you use "default" instead of "browser", as stated in this guideline:

I think this is a bit incorrect in this context. The `default` field is a fallback field when the bundler cannot figure out what export condition to use. But the `/browser` and `/node` exports are meant to be restricted to the environment. If you decide to import `/presets/browser` in Node.js, and we ship a `default` field there, it would resolve and you will get a broken import on runtime. 

One thing I considered in the past is providing stub imports for those impossible cases. Something like

```js
// noop.js
throw new Error('Your imported the wrong thing')
```

```json
{
  "exports": {
    "/presets/browser": {
      "types": "./because-types-must-come-first.d.ts",
      "default": "./noop",
      "browser": "./actual-thing"
    }
  }
}
```

I decided against this in favor of respective the fail-fast principle. This stub module simply pushed the problem one level down: from the compilation to runtime. The sooner developer finds out they are doing something wrong, the sooner they can fix it. 

This once again proves how raw the state of ESM is right now. It's hard to write for maintainers, it's hard to use for consumers. Tools don't educate developers nearly enough to emphasize module resolution and how to control it. For example, only three years into TypeScript I learned that you can (and should!) create different `tsconfig.json` files for different use cases (one for source, one for build bundle, one for tests, etc). 

I'm glad you were able to resolve it though. Just make sure you also set the `"includes"` correctly since you don't want TypeScript to treat _every_ module as a browser module.

**Comment by Khang-NT** [comment]
Did you forget to add this:
![image](https://github.com/mswjs/interceptors/assets/13332950/159dab2a-98b9-414e-9bcc-59be76d90afe)

Without exporting `browser` for `.` caused a big mess, example it will complain `FetchInterceptor` is not assignable to `Interceptor` because clearly, they're in different universes:
- `Interceptor` is taken from `./lib/node`
- `FetchInterceptor`  is taken from `./lib/browser`
