### ISSUE TITLE
Replace "uuid" with "crypto.randomUUID()"

### ISSUE THREAD

**Issue by kettanaito** [mswjs/interceptors#470]
Node.js ships with the built-in way to generate UUID via the `node:crypto` module. We should remove the `uuid` dependency and use `node:crypto` instead.

**Comment by hpohlmeyer** [comment]
Since #470 is closed now, I am adding the comment here as well:

Using `node:crypto` would break browser compatibility. As far as I know msw uses this package to defer requests until the service worker has been registered, so browser compatibility is still needed.

Using `crypto.randomUUID()` work  on https-sites, but cannot be used on http-sites, because `crypto` is `undefined` there.

**Comment by kettanaito** [comment]
@hpohlmeyer, thanks for the context around the pull request. 

> Using node:crypto would break browser compatibility.

True. However, both Node.js and browsers ships a global `crypto` object that has the `.randomUIUD()` method. This code runs the same in the browser and in Node.js:

```js
crypto.randomUUID()
```

We don't need to import `node:crypto` at all! 

> Using crypto.randomUUID() work on https-sites, but cannot be used on http-sites, because crypto is undefined there.

This is out of the scope of this package. None of the interceptors are meant to be deployed to production. I don't treat this as a blocker.

**Comment by kettanaito** [comment]
## Released: v0.26.12 🎉

This has been released in v0.26.12!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.26.12)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.26.12)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
