### ISSUE TITLE
Http2?

### ISSUE THREAD

**Issue by lox** [mswjs/interceptors#485]
I'm trying to record/replay requests to Google Cloud APIs, specifically SecretsManager, which apprears to be grpc which is over `http2`. 

Should `http2` be working with this library?

**Comment by kettanaito** [comment]
Hey, @lox. 

No, Interceptors don't support the `node:http2` module right now. I gave the docs [a quick look](https://nodejs.org/api/http2.html#client-side-example) and it seems that client/server communication is dramatically different from `node:http` so our existing interceptors simply won't work. 

You can give it a try and help us implement that support though, if you have enough insight into HTTP2 internals in Node.js. It's not on the roadmap otherwise.

**Comment by lox** [comment]
No problems @kettanaito, perhaps one day I will, not familiar enough with the internals of http2 right now either.

**Comment by kettanaito** [comment]
@lox, let me know if you come to that. We can brainstorm the implementation together.
