### ISSUE TITLE
Setting header with cookie value no longer overwrites a cookie value, it appends

### ISSUE THREAD

**Issue by noahbald** [mswjs/interceptors#631]
Hey there, I've updated `msw` from `^2.4.2` to `^2.4.5` and thus `@mswjs/interceptors` from `0.29.1` to `0.35.1`. This seems to have a changed behaviour when setting a cookie header.
I'm not too sure of the technical details, but this is the change I'm seeing.

```ts
// msw@^2.4.2
console.log(request.headers.get("cookie")); // foo=bar
request.headers.set("cookie", "foo=baz");
console.log(request.headers.get("cookie")); // foo=baz

// msw@^2.4.5
console.log(request.headers.get("cookie")); // foo=bar
request.headers.set("cookie", "foo=baz");
console.log(request.headers.get("cookie")); // foo=bar; foo=baz
```

## Workaround
```ts
import { parse, serialize } from "cookie";

const cookies = cookies.parse(request.headers.get("cookie")!);
cookies.foo = "baz"
request.headers.set(serialize(cookies));
```

**Comment by kettanaito** [comment]
## Root cause

The issue is caused by the interceptors _pushing_ recorded headers into the internal array:

https://github.com/mswjs/interceptors/blob/bb9d798e03f79d0c36869c73f740edc80f3f7a5f/src/interceptors/ClientRequest/utils/recordRawHeaders.ts#L10

So, whenever you _set_ a header on a response with that header name already present, the internal array will contain _two_ values. The `Headers` class will then treat that as multi-value header, merging its values.

```js
response.headers.set('foo', 'bar')
// internally: [ ['foo', 'bar'] ]

response.headers.get('foo', 'xyz')
// internally: [ ['foo', 'bar'], ['foo', 'xyz'] ]
```

**Comment by kettanaito** [comment]
## Released: v0.35.6 🎉

This has been released in v0.35.6!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.35.6)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.35.6)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by noahbald** [comment]
Awesome work, I can confirm the fix is working on my end 🙌

**Comment by kettanaito** [comment]
Yoo-hoo!
